insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (1, 'B89380', 'Alfred H. Baumann Free Public Library (West Paterson)', '9 Buhler Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (2, 'B95410', 'Anthony Pio Costa Memorial Library (Fairfield)', '8 Jenifer Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (3, 'B06857', 'Louis Bay 2nd Library and Community Center (Hawthorne)', '360 Macpherson Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (4, 'B88318', 'Otto Bruyns Public Library (Northfield)', '69026 Lukken Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (5, 'B14206', 'Carney’s Point Public Library (Penns Grove)', '9 Saint Paul Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (6, 'B86962', 'Clarence Dillon Public Library (Bedminster Far Hills)', '289 Lillian Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (7, 'B30860', 'William E. Dermody Public Library (Carlstadt)', '49 Dunning Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (8, 'B77996', 'Clarence Dillon Public Library (Bedminster Far Hills)', '07074 Badeau Way');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (9, 'B44042', 'Dixon Homestead Library (Dumont)', '0976 Dwight Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (10, 'B66111', 'Dowdell Library of South Amboy (South Amboy)', '1 Tomscot Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (11, 'B34984', 'Dwight D. Eisenhower Library (Totowa)', '49593 Boyd Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (12, 'B50921', 'Marie Fleche Memorial Library (Berlin)', '99 Corry Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (13, 'B48838', 'Franklin Township Free Public Library (Gloucester)', '6525 Claremont Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (14, 'B84466', 'Franklin Township Free Public Library (Somerset)', '9 Eastwood Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (15, 'B48751', 'Free Public Library of Audubon (Audubon)', '8 Kensington Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (16, 'B67623', 'Free PL of The Borough of Pompton Lakes (Pompton Lakes)', '148 Truax Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (17, 'B29512', 'Gill Memorial Library (Paulsboro)', '26246 Hudson Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (18, 'B36644', 'Margaret E. Heggan Free PL (Washington Twp Gloucester)', '193 Novick Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (19, 'B44077', 'Dixon Homestead Library (Dumont)', '0391 Dorton Pass');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (20, 'B85936', 'James H. Johnson Memorial Library (Deptford)', '0006 Susan Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (21, 'B95991', 'Johnson Public Library (Hackensack)', '9926 Northridge Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (22, 'B27415', 'James H. Johnson Memorial Library (Deptford)', '2 Sachs Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (23, 'B32643', 'John F. Kennedy Memorial Library (Wallington)', '4 Carberry Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (24, 'B35294', 'Joint Free Public Library of the Chathams (Chatham)', '3960 Southridge Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (25, 'B58906', 'Joint Free PL of Morristown & Morris Twp (Morristown-Morris Twp)', '82 Arrowood Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (26, 'B97924', 'Sally Stretch Keen Memorial Library (Vincentown)', '7 Farmco Way');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (27, 'B51461', 'John F. Kennedy Memorial Library (Wallington)', '741 Colorado Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (28, 'B18947', 'Lee Memorial Library (Allendale)', '51 Bowman Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (29, 'B98714', 'Louis Bay 2nd Library and Community Center (Hawthorne)', '94 Harper Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (30, 'B29440', 'Margare E. Heggan Free PL (Washington Twp Gloucester)', '5 Dexter Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (31, 'B53212', 'Marie Fleche Memorial Library (Berlin)', '64031 Prairieview Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (32, 'B69095', 'Maurice M. Pine Free Public Library (Fair Lawn)', '51 Monica Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (33, 'B11399', 'McCowan Memorial Library (Pitman)', '52 Bluestem Pass');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (34, 'B45111', 'Monroe Township Free Public Library (Gloucester Co)', '099 Sunnyside Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (35, 'B23108', 'Monroe Township Public Library (Middlesex Co.)', '17 Eastlawn Pass');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (36, 'B27859', 'Oceanic Free Library (Rumson)', '225 Merry Terrace');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (37, 'B41633', 'Otto Bruyns Public Library (Northfield)', '77784 Harper Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (38, 'B92249', 'Maurice M. Pine Free Public Library (Fair Lawn)', '48 2nd Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (39, 'B08858', 'Worth Pinkham Memorial Library (Ho-Ho-Kus)', '1 Riverside Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (40, 'B46018', 'Anthony Pio Costa Memorial Library (Fairfield)', '3 Lerdahl Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (41, 'B79603', 'Ridgefield Free Public Library (Ridgefield)', '04 Trailsway Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (42, 'B36692', 'Ridgefield Park Free Public Library (Ridgefield Park)', '3 Eggendart Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (43, 'B17367', 'Ruth L. Rockwood Memorial Library (Livingston)', '733 Towne Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (44, 'B83767', 'Sally Stretch Keen Memorial Library (Vincentown)', '61 Trailsway Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (45, 'B29807', 'Union Free Public Library (Friberger Park', '56425 Northport Trail');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (46, 'B84088', ' Union NJ)', '54 Katie Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (47, 'B85841', 'Veteran’s Memorial Library (Roselle Park)', '052 Chinook Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (48, 'B48431', 'W.H. Walters Free Public Library (Alpha)', '18 East Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (49, 'B49519', 'Wanaque Borough Free Public Library', '9141 Mandrake Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (50, 'B45213', 'Washington Public Library (Washington Boro/Warren Co)', '6 Miller Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (51, 'B54431', 'Washington Twp Free Public Library (Long Valley/Morris Co)', '67175 Russell Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (52, 'B46665', 'Washington Twp Public Library (Westwood/Bergen Co)', '3393 Kim Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (53, 'B00177', 'Whippanong Library Association (Whippany /Hanover Twp)', '53 Lukken Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (54, 'B42917', 'William E. Dermody Public Library (Carlstadt)', '74798 Riverside Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (55, 'B15056', 'Wood-Ridge Memorial Library', '7 Judy Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (56, 'B65719', 'Woodstown-Pilesgrove Library', '6112 Veith Way');
