insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (1, 'Tan', 'Bunhill', 'Rubinowicz', '72-461-2031', 'trubinowicz0@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (2, 'Vanya', 'Stubbington', 'Potier', '15-705-3444', 'vpotier1@sakura.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (3, 'Raddie', 'Kyles', 'Robey', '50-396-4537', 'rrobey2@paginegialle.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (4, 'Elysia', 'Kelberer', 'Suermeier', '95-158-2622', 'esuermeier3@ameblo.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (5, 'Kevina', 'MacFadden', 'Axelbee', '13-828-6119', 'kaxelbee4@java.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (6, 'Thalia', 'Bolingbroke', 'Codi', '80-712-1031', 'tcodi5@cyberchimps.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (7, 'Sabra', 'Crompton', 'Bottle', '76-552-5938', 'sbottle6@ftc.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (8, 'Alric', 'Sotham', null, '23-068-8027', 'abeddow7@adobe.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (9, 'Gaylene', 'Vidyapin', 'Lindstrom', '58-059-3214', 'glindstrom8@1und1.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (10, 'Junia', 'Cornewall', 'Grishechkin', '43-031-1266', 'jgrishechkin9@cisco.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (11, 'Wayne', 'Jura', 'Pichan', '32-093-5420', 'wpichana@blogs.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (12, 'Eugen', 'Rogeron', 'Moorhead', '39-988-4433', 'emoorheadb@goo.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (13, 'Quintin', 'Brookshaw', 'Hellyar', '75-774-7218', 'qhellyarc@ox.ac.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (14, 'Gregory', 'Fruish', 'Scampion', '44-830-5775', 'gscampiond@tiny.cc', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (15, 'Etta', 'Rowling', 'Gerren', '93-757-4141', 'egerrene@scientificamerican.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (16, 'Gil', 'St Louis', 'Rowlings', '89-552-5779', 'growlingsf@bloglines.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (17, 'Wilt', 'Swales', null, '25-743-7058', 'wcheving@ucoz.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (18, 'Paddie', 'Coakley', 'Costard', '94-077-4188', 'pcostardh@creativecommons.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (19, 'Antonia', 'Tomasini', 'Spiers', '91-880-2442', 'aspiersi@infoseek.co.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (20, 'Genia', 'Gilbert', null, '76-824-2645', 'gbillingsleyj@statcounter.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (21, 'Vonnie', 'Dawton', 'Clines', '64-817-8718', 'vclinesk@walmart.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (22, 'Pepita', 'Reading', null, '00-592-8510', 'prosenl@xinhuanet.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (23, 'Harcourt', 'Brisbane', 'Robbe', '71-288-5129', 'hrobbem@xinhuanet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (24, 'Donnamarie', 'Derkes', 'Feathersby', '99-135-5793', 'dfeathersbyn@va.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (25, 'Selia', 'Impey', 'Edie', '25-328-8492', 'sedieo@google.es', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (26, 'Kali', 'Puckrin', null, '05-497-1733', 'kabbatip@blogtalkradio.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (27, 'Correna', 'O'' Donohue', null, '95-144-4596', 'cpoupardq@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (28, 'Hermon', 'Klimaszewski', null, '37-739-8594', 'hshelpr@lycos.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (29, 'Winifred', 'Bernolet', 'Ogus', '18-790-6758', 'woguss@tinyurl.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (30, 'Maggy', 'Donnett', 'Dods', '81-214-0625', 'mdodst@deliciousdays.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (31, 'Alverta', 'Kalkhoven', 'Blakeden', '26-703-5079', 'ablakedenu@utexas.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (32, 'Mickey', 'Muldowney', 'Elmer', '97-040-9405', 'melmerv@usa.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (33, 'Oswell', 'Mattielli', 'Fairbeard', '30-744-0101', 'ofairbeardw@omniture.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (34, 'Bobby', 'Mallinson', 'Bendan', '39-667-8960', 'bbendanx@google.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (35, 'Cordula', 'Aronsohn', 'Solway', '90-839-9201', 'csolwayy@hostgator.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (36, 'Archer', 'Messenbird', 'Semmens', '94-250-1971', 'asemmensz@free.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (37, 'Ariela', 'Jeandeau', 'Agglio', '40-653-8695', 'aagglio10@ameblo.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (38, 'Darsey', 'Sprouls', 'Gaythor', '64-736-3977', 'dgaythor11@trellian.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (39, 'Rurik', 'Nice', 'Bauchop', '87-040-9011', 'rbauchop12@yale.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (40, 'Franz', 'McCumesky', 'Kleynen', '15-459-1532', 'fkleynen13@nhs.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (41, 'Germaine', 'Male', null, '15-124-0496', 'gloftus14@msn.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (42, 'Sioux', 'Boni', null, '37-671-1044', 'swinward15@live.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (43, 'Darice', 'McAvaddy', 'Beech', '33-266-3393', 'dbeech16@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (44, 'Shane', 'Pittet', null, '74-878-8249', 'sstopher17@youtube.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (45, 'Silvain', 'Eastby', null, '00-762-4680', 'sburghill18@netlog.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (46, 'Melany', 'Bohlens', null, '91-752-3207', 'mhenriksson19@omniture.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (47, 'Basilius', 'Selliman', 'Smallsman', '35-441-4958', 'bsmallsman1a@cbsnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (48, 'Geoff', 'Witty', 'Dee', '44-600-9840', 'gdee1b@taobao.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (49, 'Laverna', 'Moller', null, '71-957-9820', 'ldilleston1c@webnode.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (50, 'Elvina', 'Bulleyn', 'Wrate', '19-354-5096', 'ewrate1d@ocn.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (51, 'Rupert', 'Indruch', 'Stellino', '52-674-3400', 'rstellino1e@state.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (52, 'Karlyn', 'Lesper', 'Semerad', '35-845-2374', 'ksemerad1f@reddit.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (53, 'Anthiathia', 'Kinahan', 'Goldup', '33-889-0980', 'agoldup1g@parallels.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (54, 'Evangelia', 'Beirne', null, '61-384-8682', 'ejeanel1h@unicef.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (55, 'Pauly', 'Adrian', 'Dudden', '05-678-6107', 'pdudden1i@netvibes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (56, 'Brear', 'MacEvilly', 'Ludlam', '91-598-7327', 'bludlam1j@photobucket.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (57, 'Renell', 'Farge', 'Morin', '53-569-2218', 'rmorin1k@seattletimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (58, 'Lanny', 'Best', 'Silverthorn', '31-004-7098', 'lsilverthorn1l@zdnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (59, 'Queenie', 'Erasmus', null, '25-769-1685', 'qskene1m@intel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (60, 'Amata', 'Finnan', 'Bosson', '53-533-4723', 'abosson1n@engadget.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (61, 'Matthieu', 'Philipeaux', 'Ebbs', '48-904-6850', 'mebbs1o@loc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (62, 'Amalita', 'McIver', 'Kubec', '94-976-1401', 'akubec1p@ft.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (63, 'Hanni', 'Gorman', 'Assur', '61-183-9475', 'hassur1q@berkeley.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (64, 'Darn', 'McGeaney', 'Akker', '03-646-4659', 'dakker1r@indiatimes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (65, 'Alberto', 'Edkins', null, '63-680-2014', 'ashoutt1s@parallels.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (66, 'Dede', 'Cleave', 'Yellowlee', '88-642-9393', 'dyellowlee1t@arizona.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (67, 'Jephthah', 'Dilloway', 'Rentilll', '27-308-4896', 'jrentilll1u@biblegateway.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (68, 'Marrilee', 'Pibworth', 'Elton', '45-140-2965', 'melton1v@php.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (69, 'Ruthe', 'Pioli', 'Iacobo', '23-069-7642', 'riacobo1w@msn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (70, 'Kayle', 'Syde', 'Lexa', '12-407-9647', 'klexa1x@hostgator.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (71, 'Gregoor', 'Bridie', 'Antonnikov', '15-996-7310', 'gantonnikov1y@quantcast.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (72, 'Druci', 'Brugh', 'Birchenough', '10-720-9563', 'dbirchenough1z@w3.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (73, 'Katha', 'Grimmett', null, '94-447-3168', 'klead20@de.vu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (74, 'Candi', 'MacDonell', 'Drains', '48-764-3249', 'cdrains21@wired.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (75, 'Chip', 'Dowles', 'Lapidus', '71-773-9462', 'clapidus22@msn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (76, 'Byran', 'Brummell', null, '20-034-2751', 'bchaucer23@bandcamp.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (77, 'Isidora', 'Granham', 'Rameaux', '70-678-0706', 'irameaux24@alexa.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (78, 'Jammal', 'Fendt', 'Shower', '21-129-5214', 'jshower25@odnoklassniki.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (79, 'Thedrick', 'Ely', 'Ofen', '85-214-2094', 'tofen26@webeden.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (80, 'Henka', 'Blencowe', 'Grishukov', '94-354-8143', 'hgrishukov27@technorati.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (81, 'Cobb', 'Janew', 'Fenkel', '79-551-8780', 'cfenkel28@slate.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (82, 'Gizela', 'Lindstedt', 'Cottey', '24-308-6644', 'gcottey29@illinois.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (83, 'Roi', 'Bront', 'Warcup', '00-002-3681', 'rwarcup2a@ycombinator.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (84, 'Roddie', 'Robke', 'Brolechan', '55-253-9377', 'rbrolechan2b@blog.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (85, 'Fiorenze', 'Roddell', 'Neild', '63-701-5094', 'fneild2c@fda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (86, 'Bernadette', 'Jordine', 'Barthropp', '54-886-5157', 'bbarthropp2d@baidu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (87, 'Katey', 'Lantaff', 'Shaddick', '03-796-1803', 'kshaddick2e@cloudflare.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (88, 'Webster', 'Daines', 'Kemston', '42-803-5253', 'wkemston2f@marketwatch.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (89, 'Jena', 'Marquot', 'Artois', '58-361-8721', 'jartois2g@twitter.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (90, 'Renado', 'Dayborne', 'Adnams', '56-270-9006', 'radnams2h@dropbox.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (91, 'Ky', 'Probbings', 'Bengough', '25-525-3067', 'kbengough2i@themeforest.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (92, 'Harwilll', 'Girogetti', null, '06-973-3024', 'hvalintine2j@ed.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (93, 'Chad', 'Bothie', 'Izzatt', '68-805-4086', 'cizzatt2k@pbs.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (94, 'Kikelia', 'Ditchett', null, '45-105-7311', 'kwhates2l@google.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (95, 'Izak', 'Gladding', null, '71-438-2757', 'imaskrey2m@whitehouse.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (96, 'Beverlie', 'Purviss', 'Dyzart', '58-241-4064', 'bdyzart2n@yale.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (97, 'Merry', 'Julien', null, '46-648-2688', 'margont2o@amazon.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (98, 'Prince', 'Pedican', null, '31-074-3358', 'pibbitt2p@hugedomains.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (99, 'Joel', 'Pirolini', null, '47-503-8248', 'jvidyapin2q@amazonaws.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (100, 'Tildi', 'Dressel', 'Noone', '21-172-8978', 'tnoone2r@blogspot.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (101, 'Fern', 'Holleran', 'Dhillon', '81-190-4335', 'fdhillon2s@jalbum.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (102, 'Derry', 'Gillford', 'Paulich', '14-583-3659', 'dpaulich2t@webeden.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (103, 'Annabela', 'D''Hooghe', null, '89-133-3285', 'abedin2u@usgs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (104, 'Elinor', 'Mitkcov', null, '23-159-5725', 'enaismith2v@imdb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (105, 'Conni', 'Bradberry', 'Mabbs', '70-639-3638', 'cmabbs2w@harvard.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (106, 'Roderich', 'Wrankling', null, '99-860-8901', 'rdenyukhin2x@flickr.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (107, 'Monty', 'Rossant', 'Seymark', '02-696-9233', 'mseymark2y@jugem.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (108, 'Gerri', 'Prophet', 'Steinor', '18-401-1489', 'gsteinor2z@imdb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (109, 'Elladine', 'Marian', 'McSkin', '59-027-6021', 'emcskin30@1und1.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (110, 'Bill', 'Mettericke', null, '51-774-8074', 'bsapsford31@europa.eu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (111, 'Prentice', 'Kuzemka', 'Rontree', '62-488-6876', 'prontree32@newyorker.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (112, 'Jose', 'Boyett', 'Prop', '80-677-9350', 'jprop33@amazon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (113, 'Hogan', 'Kristof', 'Springett', '95-293-5669', 'hspringett34@ocn.ne.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (114, 'Peterus', 'Gamble', 'Danahar', '67-452-3929', 'pdanahar35@networkadvertising.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (115, 'Courtnay', 'St. Queintain', 'Klima', '60-757-5192', 'cklima36@github.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (116, 'Jonathon', 'Sargerson', 'McPhate', '74-639-1266', 'jmcphate37@businessweek.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (117, 'Yurik', 'Joriot', 'Bardnam', '02-190-3996', 'ybardnam38@reverbnation.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (118, 'Terrill', 'Axleby', null, '09-132-1931', 'tbeck39@answers.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (119, 'Ring', 'Gores', 'Ianni', '80-997-5643', 'rianni3a@google.com.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (120, 'Mahala', 'Buzin', 'Hurring', '44-664-9789', 'mhurring3b@earthlink.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (121, 'Berget', 'Hicklingbottom', 'Spinley', '11-473-4367', 'bspinley3c@behance.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (122, 'Hercule', 'Flahive', null, '44-189-0891', 'hcradoc3d@woothemes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (123, 'Flori', 'Balazin', 'Gouldsmith', '88-338-6075', 'fgouldsmith3e@imdb.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (124, 'Carey', 'Klassmann', null, '15-168-2559', 'ccrampsy3f@cbc.ca', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (125, 'Madalyn', 'Sunners', 'McGoldrick', '28-948-4041', 'mmcgoldrick3g@businesswire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (126, 'Terri', 'Tunny', 'Dunstan', '31-411-9331', 'tdunstan3h@hp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (127, 'Alanson', 'Pinhorn', null, '02-627-1198', 'acumberland3i@dot.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (128, 'Janine', 'Archdeckne', null, '70-820-4159', 'jduke3j@uiuc.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (129, 'Nataniel', 'Rickets', 'Andrei', '81-335-8018', 'nandrei3k@statcounter.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (130, 'Minerva', 'Vedyashkin', 'Killiner', '54-355-2238', 'mkilliner3l@jimdo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (131, 'Silvan', 'Lyngsted', null, '75-988-3012', 'screamen3m@jiathis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (132, 'Nadiya', 'Tebbett', 'Threadgould', '02-941-7188', 'nthreadgould3n@prweb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (133, 'Ingrid', 'Rigge', 'Clutheram', '14-706-8572', 'iclutheram3o@e-recht24.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (134, 'Kat', 'Lineham', 'Cussen', '30-513-7120', 'kcussen3p@tripadvisor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (135, 'Venus', 'Jahndel', null, '62-077-8158', 'vlesurf3q@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (136, 'Aurlie', 'Tremayle', 'Karolovsky', '60-407-4648', 'akarolovsky3r@nasa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (137, 'Alayne', 'Bigglestone', 'Willerton', '69-640-6656', 'awillerton3s@prnewswire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (138, 'Starlene', 'Billo', 'Brevitt', '35-824-4441', 'sbrevitt3t@linkedin.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (139, 'Kit', 'Hartfield', null, '37-015-1891', 'khalkyard3u@icq.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (140, 'Linnea', 'Patinkin', 'Pountain', '35-709-0578', 'lpountain3v@about.me', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (141, 'Cate', 'Millen', 'Lidgertwood', '22-211-6533', 'clidgertwood3w@gravatar.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (142, 'Analiese', 'Jolliss', 'Chazelle', '69-043-3145', 'achazelle3x@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (143, 'Marijn', 'Jennaroy', null, '75-411-8347', 'mkerwen3y@google.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (144, 'Shay', 'Keaveney', null, '97-084-0387', 'sswoffer3z@dell.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (145, 'Karna', 'Cremins', 'Mulloch', '66-728-8330', 'kmulloch40@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (146, 'Mort', 'Winwood', 'Rebillard', '70-449-1423', 'mrebillard41@nbcnews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (147, 'Hussein', 'Dunthorn', 'Dodwell', '74-761-3030', 'hdodwell42@cargocollective.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (148, 'Saloma', 'Minchella', 'Camois', '96-096-7497', 'scamois43@google.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (149, 'Lorianna', 'Jirek', 'Costain', '22-621-3838', 'lcostain44@buzzfeed.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (150, 'Tedmund', 'Habbal', 'Selesnick', '11-959-7029', 'tselesnick45@businesswire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (151, 'Ase', 'Scadden', 'Elsdon', '82-329-0624', 'aelsdon46@fda.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (152, 'Jozef', 'Chessor', 'McCarlich', '33-165-8242', 'jmccarlich47@privacy.gov.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (153, 'Edan', 'Huke', 'Nore', '47-035-6019', 'enore48@china.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (154, 'Sarge', 'Cake', null, '24-268-2660', 'spadley49@marketwatch.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (155, 'Spence', 'Pfaffel', 'Halkyard', '74-011-3183', 'shalkyard4a@nytimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (156, 'Gardie', 'Etchingham', 'D''Arrigo', '27-349-1704', 'gdarrigo4b@quantcast.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (157, 'Maryl', 'Dunsmuir', 'Emmanueli', '43-565-0646', 'memmanueli4c@disqus.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (158, 'Emmye', 'Dickson', null, '13-882-2534', 'ecocksedge4d@theatlantic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (159, 'Filide', 'Lundbeck', null, '12-522-9099', 'fjindra4e@stumbleupon.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (160, 'Christal', 'Montrose', 'Ipsly', '17-491-3545', 'cipsly4f@photobucket.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (161, 'Ignacio', 'Oswick', 'Chiverton', '05-740-4825', 'ichiverton4g@ifeng.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (162, 'Bellanca', 'Speed', null, '29-649-5525', 'bskill4h@drupal.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (163, 'Malissia', 'Aronsohn', 'Majury', '06-327-2648', 'mmajury4i@arizona.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (164, 'Wye', 'Swett', 'Yarham', '25-335-5969', 'wyarham4j@360.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (165, 'Lowrance', 'Conerding', null, '79-033-3464', 'lroyden4k@ning.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (166, 'Bucky', 'Hassekl', 'Bygrave', '87-231-0582', 'bbygrave4l@reverbnation.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (167, 'Kristo', 'Fencott', 'Wein', '08-624-4963', 'kwein4m@qq.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (168, 'Lemmy', 'Varty', 'Kingsnoad', '75-607-3204', 'lkingsnoad4n@hexun.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (169, 'Micheil', 'Scough', 'Brunini', '20-702-5373', 'mbrunini4o@seattletimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (170, 'Kristin', 'Vashchenko', 'Bass', '53-444-8333', 'kbass4p@cloudflare.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (171, 'Hermie', 'Eller', 'Corkett', '55-572-3846', 'hcorkett4q@nbcnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (172, 'Dre', 'Weild', 'Reynard', '00-667-1778', 'dreynard4r@cnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (173, 'Shannan', 'Newhouse', 'Sketh', '28-442-9903', 'ssketh4s@time.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (174, 'Chloette', 'Candie', 'Kenan', '27-602-8016', 'ckenan4t@bigcartel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (175, 'Jacintha', 'Rapps', 'Rolland', '65-567-4344', 'jrolland4u@cornell.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (176, 'Daveen', 'McCulloch', 'Coopper', '23-353-4010', 'dcoopper4v@wikia.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (177, 'Luigi', 'McNabb', 'Hritzko', '51-981-7762', 'lhritzko4w@privacy.gov.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (178, 'Imelda', 'Pavic', 'Joburn', '28-736-3669', 'ijoburn4x@myspace.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (179, 'Rancell', 'Radborn', 'Shipperbottom', '98-237-5804', 'rshipperbottom4y@dot.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (180, 'Fidole', 'Rothwell', 'Wank', '71-555-1540', 'fwank4z@twitter.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (181, 'Dev', 'Fayre', null, '27-305-9733', 'dmacneil50@so-net.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (182, 'Karol', 'Roberts', 'Casewell', '31-673-6117', 'kcasewell51@is.gd', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (183, 'Melantha', 'Getty', 'Annis', '49-865-7325', 'mannis52@360.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (184, 'Annecorinne', 'Seamons', 'Franz-Schoninger', '07-870-9232', 'afranzschoninger53@hubpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (185, 'Maegan', 'Theis', null, '65-667-8409', 'mcalrow54@shop-pro.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (186, 'Doe', 'Karadzas', 'Buckney', '65-980-0239', 'dbuckney55@java.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (187, 'Devy', 'Sutcliff', 'Pau', '81-214-2493', 'dpau56@w3.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (188, 'Nicolai', 'Pybus', 'Ladell', '10-665-2783', 'nladell57@meetup.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (189, 'Russ', 'Matitiaho', 'Cawkill', '58-706-2668', 'rcawkill58@netlog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (190, 'Artus', 'April', 'Crofts', '64-441-7516', 'acrofts59@tuttocitta.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (191, 'Roberta', 'Aykroyd', 'Tirrell', '01-441-0072', 'rtirrell5a@smh.com.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (192, 'Kary', 'Machan', 'Harower', '61-004-4385', 'kharower5b@taobao.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (193, 'Emlyn', 'Greenstock', 'Arkell', '87-185-5592', 'earkell5c@weebly.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (194, 'Cheston', 'Casarini', null, '33-940-4529', 'cetchingham5d@unblog.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (195, 'Ephrayim', 'Halesworth', 'Dempsey', '33-164-4223', 'edempsey5e@soup.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (196, 'Whittaker', 'Davitt', 'Karolewski', '28-469-6824', 'wkarolewski5f@google.nl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (197, 'Marcelle', 'Zarfati', null, '11-712-2119', 'mongin5g@amazonaws.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (198, 'Flemming', 'Vidler', 'Pinnington', '60-967-5644', 'fpinnington5h@who.int', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (199, 'Roxie', 'Jeffs', 'Pfleger', '04-822-0416', 'rpfleger5i@google.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (200, 'Debera', 'Puzey', 'Sarfatti', '52-383-8277', 'dsarfatti5j@hhs.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (201, 'Dell', 'Mathiasen', null, '45-684-1351', 'daldrich5k@cafepress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (202, 'Neall', 'Nayer', 'Weare', '92-744-0476', 'nweare5l@ustream.tv', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (203, 'Cristiano', 'Lethardy', 'Dupoy', '33-977-9427', 'cdupoy5m@friendfeed.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (204, 'Sydney', 'Talmadge', 'Craigheid', '09-836-5818', 'scraigheid5n@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (205, 'Jedd', 'Houlworth', 'Rainville', '10-218-0562', 'jrainville5o@census.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (206, 'Kristen', 'Klejin', 'Filon', '95-458-8869', 'kfilon5p@people.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (207, 'Gert', 'Sedgemond', 'Ganiford', '22-698-0531', 'gganiford5q@va.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (208, 'Augy', 'Bertelet', 'Croall', '87-778-6901', 'acroall5r@chronoengine.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (209, 'Zita', 'Spreull', null, '68-382-8780', 'ztrigg5s@uol.com.br', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (210, 'Roze', 'Messier', 'Tansley', '55-727-3606', 'rtansley5t@whitehouse.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (211, 'Hillard', 'Cottle', 'Goodsall', '96-944-6112', 'hgoodsall5u@narod.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (212, 'Johnny', 'Shreve', 'Revely', '25-811-1443', 'jrevely5v@google.com.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (213, 'Guillemette', 'Ferruzzi', null, '02-233-8911', 'gbeechcraft5w@un.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (214, 'Niel', 'Oldacres', null, '88-973-1706', 'nleborgne5x@bigcartel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (215, 'Cletus', 'Grayshan', 'Mackison', '56-214-3407', 'cmackison5y@mapy.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (216, 'Mycah', 'Sigert', 'Liddyard', '33-031-5110', 'mliddyard5z@vimeo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (217, 'Ryan', 'Peiser', null, '52-915-8227', 'rmcfarlane60@naver.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (218, 'Billy', 'Stopper', 'Gorusso', '89-833-6346', 'bgorusso61@hibu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (219, 'Bradford', 'Bader', null, '97-478-3190', 'bcleugh62@comcast.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (220, 'Aurlie', 'Slidders', null, '91-840-3653', 'ascardifeild63@simplemachines.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (221, 'Reuben', 'Zorzin', 'Huggens', '27-184-6132', 'rhuggens64@si.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (222, 'Wendi', 'Ehrat', 'Kinlock', '95-480-4017', 'wkinlock65@wikispaces.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (223, 'Zita', 'Gavigan', 'Grimmolby', '75-937-9464', 'zgrimmolby66@desdev.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (224, 'Jayne', 'McDavitt', 'Spering', '01-755-0271', 'jspering67@simplemachines.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (225, 'Shela', 'Ibberson', 'Brittle', '47-411-4436', 'sbrittle68@reverbnation.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (226, 'Gannon', 'Coppins', 'Conklin', '14-516-2873', 'gconklin69@ehow.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (227, 'Valentine', 'Erington', 'Knightley', '56-982-7068', 'vknightley6a@nyu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (228, 'Janice', 'Lazell', 'Ciubutaro', '91-222-7784', 'jciubutaro6b@salon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (229, 'Wald', 'Felton', 'Tadgell', '41-771-7937', 'wtadgell6c@foxnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (230, 'Dorthea', 'Cuningham', 'O''Loghlen', '49-292-0605', 'dologhlen6d@constantcontact.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (231, 'Meredithe', 'Duncanson', 'Waylett', '05-780-1558', 'mwaylett6e@buzzfeed.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (232, 'Augustina', 'Prattin', 'Lowdham', '14-847-9856', 'alowdham6f@yellowbook.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (233, 'Andreas', 'Lightewood', 'Ludwikiewicz', '38-118-4244', 'aludwikiewicz6g@typepad.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (234, 'Yelena', 'Goodsell', 'Pietroni', '46-491-2168', 'ypietroni6h@microsoft.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (235, 'Wilhelmina', 'Kops', 'Genike', '53-286-7103', 'wgenike6i@disqus.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (236, 'Ailsun', 'Dolman', 'Strangwood', '34-963-0058', 'astrangwood6j@oakley.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (237, 'Danielle', 'Ledgard', null, '95-850-4862', 'drolfs6k@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (238, 'Helaina', 'Goucher', 'McVittie', '68-065-5901', 'hmcvittie6l@over-blog.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (239, 'Carri', 'Brigg', 'Sephton', '78-218-4770', 'csephton6m@flickr.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (240, 'Rea', 'Marjanovic', 'Epilet', '16-657-3057', 'repilet6n@pinterest.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (241, 'Erny', 'Churchin', 'de Broke', '28-282-5110', 'edebroke6o@mail.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (242, 'Tiffy', 'Lefwich', 'Smaridge', '86-362-3037', 'tsmaridge6p@prweb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (243, 'Abbie', 'McKevany', 'Lafay', '45-489-3263', 'alafay6q@devhub.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (244, 'Hamlin', 'Everard', 'Lucian', '03-996-4276', 'hlucian6r@harvard.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (245, 'Yul', 'Jendrassik', 'Assandri', '92-423-5835', 'yassandri6s@skype.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (246, 'Vanna', 'Piniur', 'Lghan', '19-900-1958', 'vlghan6t@walmart.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (247, 'Izabel', 'Handscomb', null, '27-701-9739', 'iswinfon6u@time.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (248, 'Bab', 'Kingaby', null, '81-984-0620', 'bbitterton6v@linkedin.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (249, 'Rance', 'Lambden', 'Tattershaw', '65-361-7663', 'rtattershaw6w@seattletimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (250, 'Hewie', 'McGloin', 'Teesdale', '82-582-1637', 'hteesdale6x@storify.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (251, 'Kristi', 'Weathey', null, '34-032-5618', 'kmiko6y@dailymail.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (252, 'Rafaelita', 'Linwood', 'Mersey', '11-140-8795', 'rmersey6z@adobe.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (253, 'Vincenz', 'Perrins', 'Maurice', '15-843-1283', 'vmaurice70@addtoany.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (254, 'Howard', 'Spiby', 'Culpan', '42-360-0686', 'hculpan71@ihg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (255, 'Mack', 'Alu', 'Rookesby', '56-701-7005', 'mrookesby72@cdbaby.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (256, 'Cazzie', 'Kruse', 'Gerson', '02-841-5736', 'cgerson73@nature.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (257, 'Bax', 'Kemmer', null, '99-202-2527', 'bvern74@newyorker.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (258, 'Mag', 'Bourley', 'Linggard', '70-536-0431', 'mlinggard75@tinypic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (259, 'Siffre', 'Jereatt', 'Orts', '81-692-8158', 'sorts76@miitbeian.gov.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (260, 'Cole', 'Olding', 'Lease', '27-362-9971', 'clease77@sourceforge.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (261, 'Bert', 'Doree', 'Slaughter', '64-852-8387', 'bslaughter78@arizona.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (262, 'Heida', 'Haslock', null, '82-079-2239', 'hconnochie79@jalbum.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (263, 'Bradford', 'Casacchia', 'Cauthra', '08-509-4321', 'bcauthra7a@bing.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (264, 'Kerianne', 'Hardie', 'Yter', '66-967-4066', 'kyter7b@vistaprint.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (265, 'Oneida', 'Brenneke', null, '99-153-4848', 'omeredyth7c@businessinsider.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (266, 'Elspeth', 'Pirt', 'Chevers', '91-229-6173', 'echevers7d@hc360.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (267, 'Reilly', 'Rochford', 'Ryman', '05-743-7979', 'rryman7e@abc.net.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (268, 'Judith', 'St Ange', 'Alty', '50-407-2404', 'jalty7f@theatlantic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (269, 'Gaylord', 'Budik', 'Warmisham', '16-880-6380', 'gwarmisham7g@bandcamp.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (270, 'Charin', 'Seakin', 'Lodwick', '57-227-8797', 'clodwick7h@who.int', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (271, 'Berne', 'Mackilpatrick', 'Marunchak', '72-784-0781', 'bmarunchak7i@mashable.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (272, 'Sheffy', 'Paulino', 'Stroobant', '17-600-3187', 'sstroobant7j@bbc.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (273, 'Lebbie', 'Orton', 'Discombe', '77-902-4159', 'ldiscombe7k@apple.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (274, 'Elissa', 'Diperaus', 'Towersey', '92-839-4850', 'etowersey7l@miitbeian.gov.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (275, 'Merci', 'Willowby', 'Give', '69-314-2970', 'mgive7m@chicagotribune.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (276, 'Herby', 'Barendtsen', 'Scales', '39-119-5440', 'hscales7n@microsoft.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (277, 'Maxy', 'Rainford', 'Moorfield', '77-969-0799', 'mmoorfield7o@seesaa.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (278, 'Loralie', 'Menchenton', 'Willgoss', '31-307-0363', 'lwillgoss7p@microsoft.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (279, 'Sly', 'Twiname', 'Pendlenton', '99-917-5738', 'spendlenton7q@163.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (280, 'Damara', 'Mounfield', 'Maffetti', '33-165-2298', 'dmaffetti7r@about.me', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (281, 'Eyde', 'Bednall', 'Scutchin', '19-696-6020', 'escutchin7s@liveinternet.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (282, 'Torre', 'Pudner', 'Francescotti', '41-303-8283', 'tfrancescotti7t@wired.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (283, 'Langsdon', 'Sleney', 'Gerrans', '42-577-6813', 'lgerrans7u@desdev.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (284, 'Zorah', 'Austick', 'Cammiemile', '42-584-5130', 'zcammiemile7v@arstechnica.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (285, 'Karalynn', 'Verity', 'Ayllett', '06-498-1810', 'kayllett7w@imgur.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (286, 'Haskell', 'Griswaite', null, '40-369-9399', 'hgallihaulk7x@cbc.ca', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (287, 'Cyrille', 'Dunkerley', null, '56-143-6598', 'cgoby7y@java.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (288, 'Mirabel', 'Biesterfeld', null, '98-328-7498', 'mmaliffe7z@microsoft.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (289, 'Kilian', 'Jimmes', null, '74-483-3754', 'kney80@tuttocitta.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (290, 'Alina', 'Tschirschky', null, '09-736-8183', 'ascarratt81@amazon.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (291, 'Olvan', 'Stoggell', 'Gormley', '03-384-0890', 'ogormley82@creativecommons.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (292, 'Catrina', 'Pfeffle', 'Throssell', '64-108-5224', 'cthrossell83@reddit.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (293, 'Ewen', 'Gravett', null, '32-767-7887', 'elefeuvre84@exblog.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (294, 'Ronnie', 'Oddie', 'Graver', '05-235-1611', 'rgraver85@smh.com.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (295, 'Giacinta', 'Crosston', 'Vaskov', '03-951-6513', 'gvaskov86@ibm.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (296, 'Lalo', 'Nansom', 'Founds', '34-209-5359', 'lfounds87@indiegogo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (297, 'Erminia', 'Feechum', 'Hagard', '04-271-3660', 'ehagard88@ezinearticles.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (298, 'Valentino', 'Laidlow', 'Tanner', '40-636-8905', 'vtanner89@blogs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (299, 'Richardo', 'Scading', 'Schustl', '59-713-7110', 'rschustl8a@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (300, 'Marybelle', 'Cullagh', 'Washington', '87-877-1008', 'mwashington8b@1688.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (301, 'Ave', 'Haddon', 'Wolfenden', '34-936-1932', 'awolfenden8c@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (302, 'Marcia', 'Bruins', 'Whall', '85-919-3774', 'mwhall8d@noaa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (303, 'Kristel', 'Sherrott', 'Ibbison', '22-583-3980', 'kibbison8e@discovery.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (304, 'Michele', 'Daskiewicz', null, '95-899-3844', 'mwesley8f@addthis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (305, 'Colleen', 'Johantges', 'Kmiec', '30-078-5438', 'ckmiec8g@weibo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (306, 'Dee', 'Lillo', 'Reditt', '14-773-0792', 'dreditt8h@alibaba.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (307, 'Jacky', 'Hatwells', 'Kinnon', '15-948-0284', 'jkinnon8i@whitehouse.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (308, 'Harry', 'Gaucher', 'Hulburt', '22-552-4237', 'hhulburt8j@fotki.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (309, 'Diannne', 'Iannuzzelli', 'Godmar', '79-092-5997', 'dgodmar8k@google.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (310, 'Florenza', 'Dy', null, '25-902-2299', 'fkohen8l@businessinsider.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (311, 'Ichabod', 'Fairest', 'Purle', '27-814-7690', 'ipurle8m@jalbum.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (312, 'Virge', 'Roget', 'McCoveney', '82-786-8111', 'vmccoveney8n@bravesites.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (313, 'Stephine', 'Filipov', 'Climance', '90-505-3007', 'sclimance8o@tiny.cc', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (314, 'Bret', 'McEwan', 'Rickards', '11-714-7366', 'brickards8p@newsvine.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (315, 'Lucho', 'Spanton', 'Pinyon', '69-724-8502', 'lpinyon8q@theguardian.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (316, 'Ethan', 'Chartre', 'Crumley', '69-557-4790', 'ecrumley8r@nhs.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (317, 'Jillie', 'Holbarrow', null, '82-469-2290', 'jhubery8s@google.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (318, 'Roch', 'Kleszinski', null, '53-057-8239', 'rdanielovitch8t@dedecms.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (319, 'Sidnee', 'Mattiello', 'Stroder', '71-353-2208', 'sstroder8u@bloglines.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (320, 'Deloria', 'Parr', 'Rawcliff', '98-486-9483', 'drawcliff8v@feedburner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (321, 'Kean', 'Gaven', 'Greenhow', '20-947-2792', 'kgreenhow8w@imgur.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (322, 'Cazzie', 'Mangam', 'Vreede', '66-642-5971', 'cvreede8x@fc2.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (323, 'Ailyn', 'Igo', 'Runcieman', '17-498-2256', 'aruncieman8y@nih.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (324, 'Lammond', 'Lyster', 'Spollen', '36-620-0322', 'lspollen8z@pinterest.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (325, 'Penrod', 'Bohey', 'Rowlinson', '03-320-8546', 'prowlinson90@archive.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (326, 'Dougy', 'Crum', 'Sartin', '80-865-2138', 'dsartin91@addthis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (327, 'Fax', 'Smeeton', null, '20-943-2931', 'fleyband92@businessweek.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (328, 'Ajay', 'Grimestone', null, '97-768-5051', 'aforrestor93@redcross.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (329, 'Kinnie', 'Sincock', null, '79-080-2040', 'kinstone94@com.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (330, 'Trenna', 'Aulton', null, '67-024-6781', 'tculwen95@example.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (331, 'Alexandra', 'Currey', 'Vivians', '72-503-5026', 'avivians96@over-blog.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (332, 'Kiele', 'Dominique', 'Spooner', '62-101-9346', 'kspooner97@bloglovin.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (333, 'Inger', 'Bondy', null, '73-759-5119', 'ifranzewitch98@flickr.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (334, 'Arly', 'Crosgrove', 'Aaronsohn', '67-129-6496', 'aaaronsohn99@army.mil', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (335, 'Fernando', 'Raybould', 'Colafate', '86-884-9755', 'fcolafate9a@usda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (336, 'Bess', 'Bellelli', 'Cuffin', '30-038-9053', 'bcuffin9b@infoseek.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (337, 'Willdon', 'Godthaab', null, '72-888-5705', 'wrubens9c@indiatimes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (338, 'Luce', 'Colafate', 'Nare', '34-483-2151', 'lnare9d@unicef.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (339, 'Angy', 'Penk', 'Caseri', '30-259-5958', 'acaseri9e@linkedin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (340, 'Alidia', 'Kleeborn', null, '89-963-2834', 'ademangel9f@bizjournals.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (341, 'Delmer', 'Fingleton', 'De Giorgio', '48-379-0493', 'ddegiorgio9g@mozilla.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (342, 'Dugald', 'Poter', 'Battson', '27-118-0580', 'dbattson9h@tumblr.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (343, 'Zak', 'Lautie', 'Wincott', '71-596-3241', 'zwincott9i@nsw.gov.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (344, 'Stevie', 'Theakston', null, '78-848-4668', 'sduquesnay9j@stumbleupon.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (345, 'Osborne', 'Biles', 'Itzchaki', '68-392-0328', 'oitzchaki9k@constantcontact.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (346, 'Estell', 'McCardle', null, '94-311-8391', 'estife9l@furl.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (347, 'Barde', 'Glennon', 'Di Iorio', '69-520-5199', 'bdiiorio9m@barnesandnoble.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (348, 'Charleen', 'Dowsett', 'Santori', '31-492-3843', 'csantori9n@hao123.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (349, 'Maxie', 'Getty', 'Keaton', '39-192-1174', 'mkeaton9o@google.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (350, 'Shannon', 'Allison', 'Dumberrill', '86-335-5027', 'sdumberrill9p@ucla.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (351, 'Alfie', 'Lamanby', 'Pinxton', '28-360-9089', 'apinxton9q@friendfeed.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (352, 'Lorenza', 'Scone', 'Fanner', '98-760-8714', 'lfanner9r@histats.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (353, 'Asa', 'Ruhben', null, '90-109-7552', 'akilgour9s@bloglines.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (354, 'Isadora', 'Soda', 'Maleney', '52-887-9810', 'imaleney9t@skype.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (355, 'Augustus', 'Grieg', null, '89-451-3425', 'aflawith9u@upenn.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (356, 'Miriam', 'Matanin', 'Fortnam', '59-825-4147', 'mfortnam9v@pcworld.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (357, 'Drud', 'Kleuer', 'Donaher', '85-892-2707', 'ddonaher9w@flavors.me', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (358, 'Levin', 'Perot', 'Duchart', '21-971-1534', 'lduchart9x@businesswire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (359, 'Etti', 'Trees', 'Godfree', '80-355-4942', 'egodfree9y@diigo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (360, 'Brittani', 'Westmancoat', 'Hassey', '61-415-8897', 'bhassey9z@hexun.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (361, 'Marietta', 'Antosch', 'Balassa', '83-171-0115', 'mbalassaa0@businessweek.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (362, 'Mac', 'Behnke', 'Tumpane', '64-360-0588', 'mtumpanea1@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (363, 'Jeromy', 'Hritzko', 'Sharp', '26-473-6820', 'jsharpa2@tmall.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (364, 'Conroy', 'Hauch', null, '57-957-1743', 'cwraggsa3@washingtonpost.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (365, 'Gardie', 'Hurring', null, '11-987-4184', 'gdakhova4@godaddy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (366, 'Birch', 'Royans', 'Swinn', '90-095-3956', 'bswinna5@yelp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (367, 'Deni', 'Everitt', null, '17-799-0307', 'dcorama6@hc360.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (368, 'Beth', 'Domleo', 'Sprey', '91-537-5780', 'bspreya7@lycos.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (369, 'Farlie', 'Fagg', 'Bolingbroke', '47-122-0575', 'fbolingbrokea8@newyorker.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (370, 'Gabrielle', 'Yaldren', null, '60-216-9529', 'gbalasina9@digg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (371, 'Winthrop', 'Prigg', 'Tremlett', '07-910-9869', 'wtremlettaa@stumbleupon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (372, 'Charlie', 'Driffe', 'Wilmington', '79-266-7469', 'cwilmingtonab@globo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (373, 'Loydie', 'Cleyne', null, '41-669-4157', 'lkenerac@foxnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (374, 'Ewell', 'Lathleiff', 'Lumbly', '93-581-2560', 'elumblyad@hibu.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (375, 'Fayette', 'Grigg', 'Litchfield', '74-558-6948', 'flitchfieldae@howstuffworks.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (376, 'Avictor', 'Cuttles', 'Stitt', '27-407-8033', 'astittaf@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (377, 'Lurline', 'Vick', 'Dood', '92-952-2769', 'ldoodag@house.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (378, 'Wally', 'Caplis', 'Dowsett', '40-291-0570', 'wdowsettah@nifty.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (379, 'Shermie', 'Golsthorp', 'Zannelli', '22-695-7261', 'szannelliai@barnesandnoble.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (380, 'Nana', 'Fisbburne', 'Tinston', '13-303-7877', 'ntinstonaj@virginia.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (381, 'Dyann', 'Wayper', 'Gurden', '68-093-4119', 'dgurdenak@ustream.tv', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (382, 'Nert', 'Heffy', 'Grece', '71-097-1074', 'ngreceal@ustream.tv', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (383, 'Clemente', 'Goldman', 'Plewes', '40-533-4727', 'cplewesam@bbb.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (384, 'Carmelina', 'Vynoll', 'Kinnerley', '25-255-2322', 'ckinnerleyan@yahoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (385, 'Bartlett', 'Munday', 'Grinsted', '33-260-1695', 'bgrinstedao@nasa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (386, 'Guthry', 'Elgee', 'Gosnay', '44-183-1923', 'ggosnayap@harvard.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (387, 'Sonja', 'Jeske', null, '92-752-6497', 'sbillingslyaq@cdbaby.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (388, 'Melany', 'Wreakes', 'Frandsen', '78-889-2703', 'mfrandsenar@elegantthemes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (389, 'Aretha', 'Reddings', 'Andreutti', '43-749-5420', 'aandreuttias@addthis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (390, 'Gusti', 'Arnall', 'Buff', '60-428-8968', 'gbuffat@umich.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (391, 'Selby', 'Stroyan', 'Noon', '24-018-7764', 'snoonau@wisc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (392, 'Langsdon', 'Matusiak', 'O''Dyvoie', '72-217-4870', 'lodyvoieav@squidoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (393, 'Ranique', 'Northing', 'Hew', '20-355-5081', 'rhewaw@un.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (394, 'Heinrick', 'Lente', 'Remer', '74-809-0487', 'hremerax@elegantthemes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (395, 'Michel', 'Zaniolini', null, '58-893-8857', 'mdunsay@wisc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (396, 'Sayre', 'Chatin', 'Silson', '33-247-8324', 'ssilsonaz@geocities.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (397, 'Emilee', 'Hrishchenko', null, '73-792-7316', 'ebachurab0@newsvine.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (398, 'Clarey', 'Roebottom', 'Lumox', '15-321-0728', 'clumoxb1@globo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (399, 'Issie', 'Vanetti', 'Marriner', '76-571-7463', 'imarrinerb2@chicagotribune.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (400, 'Ashley', 'Eakins', 'Denkin', '78-002-0283', 'adenkinb3@usa.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (401, 'Jacquelyn', 'Buddleigh', 'Coales', '92-891-4995', 'jcoalesb4@chron.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (402, 'Vonnie', 'Cruft', 'Pawlik', '45-207-2475', 'vpawlikb5@stanford.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (403, 'Reynold', 'Sherwin', null, '73-749-6517', 'rdebrettb6@princeton.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (404, 'Aymer', 'Fatkin', 'Seyffert', '47-353-5587', 'aseyffertb7@forbes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (405, 'Dick', 'Rivelin', 'Arzu', '71-090-4287', 'darzub8@tripadvisor.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (406, 'Paulette', 'Gelland', 'Meaton', '45-541-0460', 'pmeatonb9@state.tx.us', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (407, 'Darsey', 'Mattecot', null, '89-883-4652', 'dstarbeckba@go.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (408, 'Myrna', 'Blodgett', 'Geibel', '98-109-2584', 'mgeibelbb@gnu.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (409, 'Chevy', 'Dearth', 'Fairbard', '51-574-9461', 'cfairbardbc@nydailynews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (410, 'Allissa', 'D''Adamo', 'Lebbern', '47-342-5916', 'alebbernbd@senate.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (411, 'Rorie', 'Chidgey', 'Ricketts', '98-430-5475', 'rrickettsbe@samsung.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (412, 'Joann', 'Liggins', 'Bocken', '44-406-8741', 'jbockenbf@free.fr', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (413, 'Maddy', 'Cremin', 'Da Costa', '30-251-3624', 'mdacostabg@spiegel.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (414, 'Mable', 'Massard', 'Cremins', '81-698-0032', 'mcreminsbh@edublogs.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (415, 'Willamina', 'Ambroziak', null, '20-506-3984', 'wartheybi@ask.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (416, 'Randi', 'Bauldrey', 'Wallach', '29-936-9455', 'rwallachbj@acquirethisname.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (417, 'Russell', 'Dickinson', null, '19-064-2486', 'rborleybk@mapquest.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (418, 'Danice', 'Khan', 'MacMeeking', '30-680-0246', 'dmacmeekingbl@netlog.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (419, 'Adore', 'Sings', 'Brahmer', '84-052-0751', 'abrahmerbm@usda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (420, 'Robinia', 'Togher', 'Hamnett', '77-866-0486', 'rhamnettbn@netscape.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (421, 'Shayla', 'Hexum', 'Maddams', '65-002-9961', 'smaddamsbo@cmu.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (422, 'Quinton', 'Huerta', null, '94-031-6378', 'qmaplethorpbp@bloglines.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (423, 'Guendolen', 'Fransewich', 'Bartholomaus', '10-370-1879', 'gbartholomausbq@vkontakte.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (424, 'Damara', 'Niezen', null, '73-842-2159', 'dmoseybr@washington.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (425, 'Germana', 'Sorley', 'Neiland', '73-871-8467', 'gneilandbs@drupal.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (426, 'Rozamond', 'Petrovykh', null, '62-686-5407', 'revesbt@mayoclinic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (427, 'Derby', 'Grave', null, '39-516-3290', 'dschnitterbu@ezinearticles.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (428, 'Holt', 'Jindra', 'Trayton', '83-989-3226', 'htraytonbv@columbia.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (429, 'Stacy', 'Matzen', 'Timmens', '90-531-9467', 'stimmensbw@mail.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (430, 'Alric', 'Chazerand', 'Mayne', '71-897-9262', 'amaynebx@youku.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (431, 'Gaby', 'Leachman', null, '47-001-7723', 'gdallossoby@php.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (432, 'Bunny', 'Gallaher', null, '09-771-8092', 'bsuggebz@ibm.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (433, 'Buddy', 'Venny', 'Yekel', '61-233-5050', 'byekelc0@sogou.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (434, 'Manny', 'Celler', null, '83-871-0237', 'mcolqueranc1@google.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (435, 'Ulick', 'Grundle', 'Atton', '22-278-3065', 'uattonc2@rambler.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (436, 'Angelo', 'Bevan', 'MacEvilly', '96-863-2011', 'amacevillyc3@wordpress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (437, 'Chrysa', 'Lisle', 'Steers', '46-076-9634', 'csteersc4@npr.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (438, 'Ashlen', 'Ainsworth', 'Bener', '21-924-4348', 'abenerc5@elpais.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (439, 'Antony', 'Tynemouth', null, '21-918-2366', 'abrookc6@github.io', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (440, 'Ernst', 'Riby', null, '29-707-7785', 'eblakebroughc7@bloglines.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (441, 'Renard', 'Kitteridge', 'Melhuish', '33-641-4851', 'rmelhuishc8@ftc.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (442, 'Lynnet', 'Molen', null, '21-663-6532', 'lhadwinc9@geocities.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (443, 'Keefe', 'Fenney', 'Blewis', '88-886-1036', 'kblewisca@google.es', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (444, 'Roze', 'Hawney', null, '93-542-8059', 'rbrowncb@weibo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (445, 'Livvy', 'Strephan', null, '30-397-6925', 'lkayzercc@hhs.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (446, 'Tremayne', 'Nesey', 'Carlsen', '64-226-5686', 'tcarlsencd@unesco.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (447, 'Waiter', 'Rushton', 'Stockford', '27-045-3123', 'wstockfordce@telegraph.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (448, 'Lorilee', 'Barkaway', 'Madre', '18-384-6241', 'lmadrecf@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (449, 'Lynette', 'Pirolini', null, '91-340-9087', 'ledinboroughcg@dailymotion.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (450, 'Edan', 'Spens', 'Asp', '76-035-6228', 'easpch@constantcontact.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (451, 'Leola', 'Lardier', 'Dowry', '65-061-0926', 'ldowryci@nationalgeographic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (452, 'Louie', 'Counter', null, '55-549-0372', 'lkennicottcj@disqus.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (453, 'Marcile', 'Gerred', null, '02-847-3294', 'mcheethamck@behance.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (454, 'Worthington', 'Padell', null, '28-190-6706', 'wpickfordcl@aol.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (455, 'Kellie', 'Mattiacci', null, '11-939-5768', 'kfruchtercm@cnbc.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (456, 'Curran', 'Blincowe', 'Gilleon', '59-077-8046', 'cgilleoncn@mlb.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (457, 'Taber', 'O''Logan', 'Pedden', '58-622-4285', 'tpeddenco@webmd.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (458, 'Claude', 'Jelleman', null, '81-633-3527', 'cchidwickcp@latimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (459, 'Carlen', 'Parsonson', 'Cope', '70-089-5673', 'ccopecq@icq.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (460, 'Joe', 'Laidlow', 'de Glanville', '81-901-8295', 'jdeglanvillecr@webmd.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (461, 'Berenice', 'Kingzett', null, '49-242-2813', 'bvittorecs@ocn.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (462, 'Aurelea', 'Armor', 'Marrison', '22-414-4994', 'amarrisonct@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (463, 'Demetri', 'Sallans', null, '85-600-9447', 'dvickcu@businesswire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (464, 'Roland', 'Vaen', 'Conaghan', '32-684-6401', 'rconaghancv@umn.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (465, 'Stephani', 'Bartoszewicz', 'Baseggio', '47-971-1837', 'sbaseggiocw@goo.gl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (466, 'Lewie', 'Stilgoe', 'Baert', '92-164-6448', 'lbaertcx@shop-pro.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (467, 'Genevra', 'Piatto', null, '93-773-6705', 'gjansemacy@gravatar.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (468, 'Andrey', 'O''Keeffe', null, '98-386-4552', 'abastablecz@census.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (469, 'Perla', 'Cobon', 'Garrity', '17-029-9066', 'pgarrityd0@mlb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (470, 'Forester', 'Skellorne', 'Deakan', '76-197-9118', 'fdeakand1@youtube.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (471, 'Bartram', 'Willatts', 'Swann', '88-136-7930', 'bswannd2@home.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (472, 'Rodi', 'Berrington', 'Pawlaczyk', '82-204-6944', 'rpawlaczykd3@jimdo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (473, 'Berty', 'Grute', 'Kibblewhite', '73-372-5375', 'bkibblewhited4@si.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (474, 'Morse', 'Kann', 'Rolston', '32-256-6702', 'mrolstond5@flavors.me', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (475, 'Sadie', 'Jillard', 'Brusin', '04-538-4941', 'sbrusind6@bloglovin.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (476, 'Eldon', 'Tanman', 'Kleeborn', '36-699-9749', 'ekleebornd7@businessinsider.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (477, 'Jedidiah', 'Kopke', null, '23-725-0457', 'jscaddingd8@wikimedia.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (478, 'Issie', 'Ponte', 'Pontain', '14-749-9180', 'ipontaind9@php.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (479, 'Mattie', 'Aplin', null, '50-941-6060', 'mnicolda@infoseek.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (480, 'Trumaine', 'Dobbin', 'Nielson', '39-324-8168', 'tnielsondb@tripadvisor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (481, 'Cassondra', 'Aleksic', 'Clifft', '62-219-0378', 'cclifftdc@icq.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (482, 'Clemmie', 'Emmens', null, '10-110-2122', 'cgatecliffedd@yale.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (483, 'Jodie', 'Churching', null, '63-201-9825', 'jlangede@g.co', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (484, 'Jessika', 'Dorricott', 'Dryden', '07-567-6845', 'jdrydendf@oracle.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (485, 'Julian', 'Pryor', 'O''Hanley', '93-513-9028', 'johanleydg@columbia.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (486, 'Philip', 'Maber', 'Daymont', '98-675-3634', 'pdaymontdh@va.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (487, 'Sissy', 'Simmgen', 'Ansell', '03-256-1561', 'sanselldi@vkontakte.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (488, 'Katy', 'Kinglesyd', 'Grenfell', '17-608-5490', 'kgrenfelldj@networkadvertising.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (489, 'Danny', 'Yepiskopov', 'Stirgess', '00-993-3100', 'dstirgessdk@deviantart.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (490, 'Claudian', 'Fanstone', 'Korpolak', '45-851-3681', 'ckorpolakdl@cargocollective.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (491, 'Jan', 'Dominichetti', 'Bushby', '79-286-7088', 'jbushbydm@jimdo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (492, 'Brion', 'Pothergill', 'Cathie', '56-929-9435', 'bcathiedn@twitpic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (493, 'Vanessa', 'Windus', 'Riddington', '12-469-8121', 'vriddingtondo@google.es', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (494, 'Lillian', 'Collyer', 'Tolhurst', '63-960-9119', 'ltolhurstdp@simplemachines.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (495, 'Dredi', 'Tremmel', 'Guerrin', '14-837-4561', 'dguerrindq@booking.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (496, 'Kass', 'Batson', 'Thurner', '42-294-3021', 'kthurnerdr@thetimes.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (497, 'Fairlie', 'Perett', 'Klaassens', '32-701-8255', 'fklaassensds@wunderground.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (498, 'Stormie', 'Bastard', null, '44-246-3557', 'sdalstondt@dedecms.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (499, 'Jerry', 'Brackpool', null, '41-726-4175', 'jfairleighdu@studiopress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (500, 'Tynan', 'Lanchester', 'Liddall', '02-359-8078', 'tliddalldv@free.fr', null);
